language: c

addons:
    apt:
        packages:
            - build-essential
            - automake
            - autoconf
            - libtool
            - pkg-config
            - intltool
            - autoconf-archive
            - libpcre3-dev
            - libglib2.0-dev
            - libgtk-3-dev
            - libxml2-utils
            - gnome-common

script: ls -l && ./autogen.sh && ./configure && make
