language: c
compiler: gcc
sudo: required
dist: trusty
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:ricotz/testing -y
  - sudo apt-get -qq update
  - sudo apt-get install -y automake autoconf libtool pkg-config intltool autoconf-archive libpcre3 libpcre3-dev libglib2.0-dev libgtk-3-dev libxml2-utils
script:
  - ./autogen.sh
  - ./configure
  - make
